version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    restart: 'always'
    depends_on:
      - backend
      - db
  backend:
    build: ./backend
    restart: 'always'
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=women_soccer
      - DB_PORT=3306
    ports:
      - 3001:3001
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    cap_add:
      - SYS_NICE
