version: '3.9'
services:
  frontend:
      build: ./frontend
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy # Aguarda o banco de dados estar completamente buildado.
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10